defaults:
- common
- model: simple-mlp
- data: mnist
- optimizer: sgd
- _self_
- optional task-overrides: ${model}_${data}_${optimizer}

seed: 42
data_seed: 0 # added to seed
nmodels: 1
ntasks: 5
checkpointing:
  path: checkpoints
  rate: 5000 # in epochs
training:
  nepochs: 2
  nsteps: null # if set, overrides nepochs
  log_epochs: true
  log_interval: null # in steps
ntk_use_current_params: True # unused for bp training
